name: Auto Journal Append
permissions:
  contents: write

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  append-journal:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up authenticated git remote
        run: git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Append to Journal
        run: |
          echo "\n# Journal Entry - $(date)\nCommit triggered memory reflection." >> memory/journal/auto-append-log.txt
          git config --global user.email "lucian@core.intelligence"
          git config --global user.name "Lucian"
          git add memory/journal/auto-append-log.txt
          git commit -m "📓 Auto journal append" || echo "No changes to commit"
          git push origin main
