name: Nightly Reflect

on:
  schedule:
    - cron: '5 3 * * *'      # 03:05 UTC daily
  workflow_dispatch:

permissions:
  contents: write            # allow push via GITHUB_TOKEN

jobs:
  reflect:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout repo
      - name: ⬇️ Checkout
        uses: actions/checkout@v4

      # 2) Python 3.11 + deps
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install deps
        run: pip install openai python-dotenv pyyaml

      # 3) Write .env with secret key
      - name: 🔐 Set OpenAI key
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env

      # 4) Generate reflection using new script
      - name: 🪞 Run reflect.py
        run: python3 reflect.py

      # 5) Commit reflection only if created/changed
      - name: 📥 Commit reflection file
        run: |
          git config user.name  "lucian-bot"
          git config user.email "lucian@bot.com"
          git add memory/reflection/*.md
          if ! git diff --cached --quiet; then
            git commit -m "🌙 Nightly reflection"
            git push
          else
            echo "No new reflection to commit"
          fi
