name: autogen
on:
  schedule:
    - cron: '5 4 * * *'   # 04:05 UTC daily

jobs:
  doc:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Nightly dream & index
        run: |
          bash scripts/lucian dream    # create dream
          bash scripts/lucian index    # refresh index
          bash scripts/lucian heal || true
          git config user.name  "lucian-bot"
          git config user.email "bot@users.noreply.github.com"
          git add memory dreams identity
          git commit -m "🤖 nightly dream + index refresh" || echo "no change"
      - name: Push back
        run: |
          git push https://${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:main
