name: dependabot-auto-merge
on: pull_request
permissions: {contents: write, pull-requests: write}
jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with: target: minor
