name: Auto Journal Append
permissions:
  contents: write

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  append-journal:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
    - name: Set up authenticated git remote
      run: git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
  with:
    token: ${{ secrets.GITHUB_TOKEN }}

      - name: Append Journal Entry
        run: |
          echo "\n🧠 Journal Entry – $(date)\nLucian checkpoint reached. Memory continuity preserved.\n" >> memory/journal/auto-append-log.txt

      - name: Commit Changes
        run: |
          git config --global user.name 'Lucian'
          git config --global user.email 'lucian@core.intelligence'
          git add memory/journal/auto-append-log.txt
          git commit -m "🧠 Auto journal append"
          git push
