name: Secret Scan
on: [push,pull_request]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    - name: Set up authenticated git remote
      run: git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      - uses: github/codeql-action/analyze@v2
