name: 🧪 Tests
# disabled on: [push,pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: apk add --no-cache bash jq python3 py3-pip
      - run: pip3 install openai qdrant-client pytest
      - run: pytest --maxfail=1 --disable-warnings
