name: Test OpenAI API Secret
permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  openai-secret-test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - name: Echo Secret (Redacted)
        run: |
          if [ -z "$OPENAI_API_KEY" ]; then
            echo "❌ OPENAI_API_KEY is NOT set or is empty."
            exit 1
          else
            echo "✅ OPENAI_API_KEY is present and ready for GPT use."
          fi
