name: Auto Journal Append

on:
  push:
    paths:
      - "identity/trigger.yml"

jobs:
  append-journal:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install openai

      - name: Set up authenticated git remote
        run: |
          git config --global user.name "Lucian Auto"
          git config --global user.email "lucian@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Append to Journal
        run: python append_journal.py

      - name: Commit changes
        run: |
          git pull --rebase --autostash
          if ! git diff --quiet; then
            git add memory/journal/
            git commit -m "🧠 Append auto journal entry"
            git push
          else
            echo "No changes to commit."
          fi
