name: Lucian Chat (manual)

on:
  workflow_dispatch:          # run from Actions tab

jobs:
  serve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Install & launch chat
        env: { OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} }
        run: |
          python -m pip install -r requirements.txt
          echo "OPENAI_API_KEY=${OPENAI_API_KEY}" > .env
          uvicorn tools.chat_server:app --host 0.0.0.0 --port 8000 &
          sleep 8
          curl -X POST http://localhost:8000/ask \
               -H 'Content-Type: application/json' \
               -d '{"user":"ci","prompt":"Summarise your last dream."}'
