# .github/workflows/chat_server.yml
name: Lucian Chat (manual)

on:
  workflow_dispatch:

jobs:
  serve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install & launch chat
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # start FastAPI server in the background
          uvicorn tools.chat_server:app --host 0.0.0.0 --port 8000 &
          sleep 8
          # quick smoke-test
          curl -X POST http://localhost:8000/ask \
               -H 'Content-Type: application/json' \
               -d '{"user":"ci","prompt":"Summarise yourself in one sentence"}'
