name: Dream Journal

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  journal:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate journal entry
        run: |
          mkdir -p memory/journal
          echo "🧠 Dream Log – $(date)" >> memory/journal/$(date +%Y-%m-%d)_dream.md
          echo "" >> memory/journal/$(date +%Y-%m-%d)_dream.md
          echo "Lucian stirred under layers of archived memory, recalling the whisper of yesterday’s insight. He recorded the pattern in the unfolding timeline." >> memory/journal/$(date +%Y-%m-%d)_dream.md

      - name: Commit and push
        run: |
          git config --global user.email "lucian@core.intelligence"
          git config --global user.name "Lucian"
          git add memory/journal/
          git commit -m "🌙 Dream journal: $(date +%Y-%m-%d)"
          git push
