name: Push Test
on:
  workflow_dispatch:
jobs:
  push-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Make a tiny change
        run: echo "push test $(date)" >> memory/journal/push-test-log.txt
      - name: Commit & Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "Lucian"
          git config user.email "lucian@core.intelligence"
          git add memory/journal/push-test-log.txt
          git commit -m "🔁 Workflow push test"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
