name: Weekly Metrics Charts
on:
  schedule:
    - cron: '30 12 * * SUN'
  workflow_dispatch:
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: |
          python -m pip install --upgrade pip
          pip install matplotlib pandas
      - run: python tools/collect_metrics.py
      - run: python tools/viz_dashboard.py
      - run: |
          git config user.name  "lucian-bot"
          git config user.email "lucian@bot.com"
          git add memory/system/*.csv memory/system/*.png
          git commit -m "📈 Weekly metrics dashboard" || echo "no changes"
          git push
